apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpd-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpd-web
    spec:
      containers:
      - name: httpd-web
        image: devalrajumahesh/kubernetes:tagname
        ports:
        - containerPort: 80
